### PR TITLE
Fix issue with app namespaces configuration

### PR DESCRIPTION
**Pull request by Roming22**
In [RHTAPBUGS-1168](https://issues.redhat.com//browse/RHTAPBUGS-1168) a user reported that the Pipelines to configure the namespaces sometime failed. The log extract seemed to show that the failure was because a task was not available yet. Therefore a safeguard has been added to make sure the referenced task is available before creating the pipelines.

### CODE REVIEW

**Comment by Roming22** [comment]
@xinredhat Any chance you can test my branch before I merge this fix for RHTAPBUGS-1168?

If that does not solve the problem, please get the YAML of the PipelineRun that's created on the namespace that's being configured. Also let me know if trying to rerun the PipelineRun is successful.

**Comment by xinredhat** [comment]
> @xinredhat Any chance you can test my branch before I merge this fix for RHTAPBUGS-1168?

@Roming22 I can verify it locally, I will share the result today.

**Comment by xinredhat** [comment]
@Roming22 I verified this PR locally a few times and I am sure your PR fixed it. thank you for the quick fix.

**Pull request merged**
