### PR TITLE
Auto configure known developer namespaces

### PR DESCRIPTION
**Pull request by Roming22**
* Setup git token

### CODE REVIEW

**Comment by Roming22** [comment]
@flacatus Can you check which the installer is failing? I've added new env variables to the values.yaml (`GITOPS__GIT__TOKEN` and `QUAY__TOKEN`), so maybe it's breaking the CI.

**Comment by prietyc123** [comment]
> @flacatus Can you check why the installer is failing? I've added new env variables to the values.yaml (`GITOPS__GIT__TOKEN` and `QUAY__TOKEN`), so maybe it's breaking the CI.

Correct we are looking into it. Thanks for pointing it out.

**Comment by prietyc123** [comment]
> @flacatus Can you check why the installer is failing? I've added new env variables to the values.yaml (GITOPS__GIT__TOKEN and QUAY__TOKEN), so maybe it's breaking the CI.

https://github.com/openshift/release/pull/49595 should fix this

**Pull request merged**
