### PR TITLE
0.0/fix/release

### PR DESCRIPTION
**Pull request by Roming22**

### CODE REVIEW

**Comment by flacatus** [comment]
servername: 'redhat-developer-hub-rhtap.apps.rhtap-4-14-us-east-2-5fd88.ci.stonesoupengineering.com',
          alpnProtocol: false,
          authorized: false,
          authorizationError: 'SELF_SIGNED_CERT_IN_CHAIN',

**Comment by Roming22** [comment]
Force merge because the issue is linked to DH 1.2.

**Pull request merged**
