### PR TITLE
enable new argocd plugin in rhtap-installer

### PR DESCRIPTION
**Pull request by karthikjeeyar**
This PR enables new argocd frontend plugin in RHTAP and disables the roadie's argocd frontend plugin

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by karthikjeeyar** [comment]
Looking at the failed pipelinerun, RHTAP-install task is failing 🤔 

```
 Error: open private-values.yaml: no such file or directory
 ```

image

**Comment by xinredhat** [comment]
@karthikjeeyar I am looking into it

**Comment by Roming22** [comment]
This PR will most likely be rejected in favor of https://github.com/redhat-appstudio/rhtap-cli/pull/57 (new installer).

**Comment by Roming22** [comment]
Repo is deprecated

**Pull request closed without merging**
