### PR TITLE
Add Sonar

### PR DESCRIPTION
**Pull request by jkopriva**

### CODE REVIEW

**Comment by Roming22** [comment]
@jkopriva the yamlint linter has issues with Helm template syntax, which is why it's currently failing. You can ask me to merge the PR if the other tests are OK.

**Comment by jkopriva** [comment]
@Roming22 Hi, thanks! Can you please merge it? Afterwards we should have something in here: https://sonarcloud.io/project/configuration?id=redhat-appstudio_rhtap-installer Thank you!

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
