### PR TITLE
updated revision of task rhtap-installer

### PR DESCRIPTION
**Pull request by xinredhat**
rh-pre-commit.version: 2.1.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by prietyc123** [comment]
I think we need to add more exact logs in rhtap e2e to debug the failure. @xinredhat Can you please create Jira for this issue to get tackled sometime. I found this error but couldn't find why the plr failed for the component

```
pipelinesascode.tekton.dev  Repository  rhtap-app-development  l0us28xkp-java-quarkus-repository         Synced                        repository.pipelinesascode.tekton.dev/l0us28xkp-java-quarkus-repository unchanged
[e2e-test] 
[e2e-test]       at log (src/utils/argocd.ts:51:17)
[e2e-test] 
[e2e-test]   console.log
[e2e-test]     Extracted image: quay.io/rhtap_qe/rhtap-qe:cf0386871b32e3afe0c09db14765adf9d49a6f1e@sha256:c42773e3d47955d2df46b4d685dc67a4285039e18d5f42f20d3ae68f4f1744b8
[e2e-test] 
[e2e-test]       at GitHubProvider.log [as extractImageFromContent] (src/apis/git-providers/github.ts:213:25)
[e2e-test] 
[e2e-test]   console.log
[e2e-test]     Found pipeline run l0us28xkp-java-quarkus-gitops-on-pull-request-clxkk
[e2e-test] 
[e2e-test]       at Kubernetes.log [as getPipelineRunByRepository] (src/apis/kubernetes/kube.ts:157:29)
[e2e-test] 
[e2e-test]   console.error
[e2e-test]     Pipeline run 'm0c8hkyx0-java-quarkus-gitops-on-pull-request-2n84g' failed.
[e2e-test] 
[e2e-test]       207 |                         return true;
[e2e-test]       208 |                     } else if (pipelineHasFailed) {
[e2e-test]     > 209 |                         console.error(`Pipeline run '${name}' failed.`);
[e2e-test]           |                                 ^
[e2e-test]       210 |                         return false;
[e2e-test]       211 |                     }
[e2e-test]       212 |                 }
[e2e-test] 
[e2e-test]       at Kubernetes.error [as waitPipelineRunToBeFinished] (src/apis/kubernetes/kube.ts:209:33)
[e2e-test]       at Object.<anonymous> (tests/gpts/gitlab/suites-config/gitlab_advanced_suite.ts:266:34)
```

**Comment by xinredhat** [comment]
this time all [tests](https://console.redhat.com/preview/application-pipeline/workspaces/rhtap-shared/applications/rhtap-installer-release-1-0-2/pipelineruns/rhtap-installer-release-1-0-2-42858-b8wd7) failed

**Comment by flacatus** [comment]
pipelinerun is in the log:

`m0c8hkyx0-java-quarkus-gitops-on-pull-request-2n84g`

**Review by Roming22 — APPROVED** [review]

**Pull request closed without merging**
