### PR TITLE
fix: escape chars when setting values

### PR DESCRIPTION
**Pull request by Roming22**

### CODE REVIEW

**Comment by xinredhat** [comment]
could you fix the following issues?
1. yamllint
```
[yaml-lint] ./chart/values.yaml
[yaml-lint]   54:19     error    too many spaces after colon  (colons)
[yaml-lint]   69:20     error    too many spaces after colon  (colons)
[yaml-lint]   125:18    error    trailing spaces  (trailing-spaces)
```

2. shellcheck
```
shellcheck] In ./bin/make.sh line 343:
[shellcheck]       VALUE="$(echo $VALUE | sed -e "s:':'\\\\'':g")"
[shellcheck]                ^-- SC2001 (style): See if you can use ${variable//search/replace} instead.
[shellcheck]                     ^----^ SC2086 (info): Double quote to prevent globbing and word splitting.
[shellcheck] 
[shellcheck] Did you mean: 
[shellcheck]       VALUE="$(echo "$VALUE" | sed -e "s:':'\\\\'':g")"
```

**Comment by xinredhat** [comment]
It looks good me besides the above errors

**Comment by Roming22** [comment]
@xinredhat Fixed.

**Comment by Roming22** [comment]
Force merging becacause of the current issue with the TPA installei

**Pull request merged**
